### ISSUE TITLE
License as env variable not getting picked up

### ISSUE THREAD

**Issue by grrywlsn** [lensesio/lenses-docker#7]
Hi,

I'm trying a deployment of the container in Kubernetes, and as suggested in the readme, I'm passing in the environment variable LICENSE with the json of license.json. The container fails to start correctly with the following error:

`2018-06-20 11:13:58,506 ERROR [c.l.k.l.Main$:155] Can not read the license file:/data/license.json`

I've tested with version 2.0 and 2.0.11 - both fail to start. Is there something else that needs to be done for it to pick up the license via env variable?

For context: I'm using only environment variables to pass in all settings - I'm not mounting a lenses.conf or security.conf file.

**Comment by Antwnis** [comment]
@grrywlsn I am assuming that you have i) received a license file and ii) you are mounting the license file into the docker with the `-v` parameter 

Also can join our Slack channel @ https://launchpass.com/landoop-community so we can better assist you in real-time ?

**Comment by grrywlsn** [comment]
I do have a valid license file, but it didn't get picked up as an environment variable.

I've got the deployment to work by passing it in as a ConfigMap to appear as a file at /mnt/secrets/license.json but that's less ideal; an environment variable (which the docs suggest should work) would be cleaner imo.

**Comment by andmarios** [comment]
Hmm, this is funny because we do use this functionality internally as well —alas not in kubernetes—, so I consider it well tested.

Let me do some tests on k8s and come back to you.

**Comment by andmarios** [comment]
Hi @grrywlsn. I can't reproduce it locally, so I need some help.

Below you'll find an example of how I added the license and other secrets in my kubernetes yaml description. The example below should work if you replace your cluster's addresses and license.

A possible cause for the issue, is that the license is in json format, which can be interpreted as part of the yaml rather than just a value. Please notice how in my example I set the license value to be interpreted as a literal:
```
      - name: LICENSE
        value: |
          {"source":"Landoop LTD","clientId":"andmarios","details":"Lenses","key":"a-very-big-string"}
```

The configuration I just tested:
```
apiVersion: v1
kind: Pod
metadata:
  name: lenses
  labels:
    name: lenses
spec:
  containers:
  - name: lenses-runtime
    image: landoop/lenses:latest
    ports:
      - containerPort: 9991
    env:
      - name: LENSES_PORT
        value: "9991"
      - name: LENSES_JMX_PORT
        value: "9015"
      - name: LENSES_KAFKA_BROKERS
        value: PLAINTEXT://kafka:9092
      - name: LENSES_ZOOKEEPER_HOSTS
        value: |
          [
            {url: "kafka:2181", jmx: "kafka:9585"}
          ]
      - name: LENSES_SCHEMA_REGISTRY_URLS
        value: |
          [
            {url: "http://kafka:8081", jmx: "kafka:9582"}
          ]
      - name: LENSES_CONNECT_CLUSTERS
        value: |
          [
            {
              name: "dev",
              urls: [
                {url: "http://kafka:8083", jmx: "kafka:9584"}
              ],
              statuses: "connect-statuses",
              configs: "connect-configs",
              offsets: "connect-offsets"
            }
          ]
      - name: LENSES_SECURITY_MODE
        value: BASIC
      - name: LENSES_HEAP_OPTS
        value: "-Xmx1G"
      - name: LENSES_SECURITY_USERS
        value: |
          [
            {"username": "admin", "password": "admin", "displayname": "Lenses Admin", "groups": ["adminGroup"]},
            {"username": "read", "password": "read", "displayname": "Read Only", "groups": ["readGroup"]}
          ]
      - name: LENSES_SECURITY_GROUPS
        value: |
          [
            {"name": "adminGroup", "roles": ["admin", "write", "read"]},
            {"name": "readGroup",  "roles": ["read"]}
          ]
      - name: LICENSE
        value: |
          {"source":"Landoop LTD","clientId":"andmarios","details":"Lenses","key":"a-very-big-string"}
```

**Comment by Antwnis** [comment]
Is the above ^ helping @grrywlsn

**Comment by grrywlsn** [comment]
Thanks, that works. I had wrapped the licence JSON in square brackets, like LENSES_ZOOKEEPER_HOSTS. Removing the brackets as you've shown for LICENSE above fixed it. Seems an inconsistence more than a bug, I guess?
